/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FkQLete9amt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import logo from '@/app/assets/logo-green.png';

export default function NavBar() {
  return (
    <header style={{width: '100%', height: '100%', paddingLeft: 35, paddingRight: 35, background: 'white', borderBottom: '1px rgba(215, 215, 215, 0.70) solid', justifyContent: 'space-between', alignItems: 'center', display: 'inline-flex'}}>
        <div style={{justifyContent: 'flex-start', alignItems: 'center', gap: 20, display: 'flex'}}>
            <img style={{width: 167.13, height: 46, position: 'relative'}} src={logo} />
            <div style={{height: 36, paddingLeft: 14, paddingRight: 14, paddingTop: 4, paddingBottom: 4, background: '#F6F8FF', borderRadius: 10, justifyContent: 'flex-start', alignItems: 'center', gap: 12, display: 'flex'}}>
                <div style={{width: 16, height: 16, position: 'relative'}}>
                    <div style={{width: 12, height: 12, left: 2, top: 2, position: 'absolute', border: '1.33px #9CA3AF solid'}}></div>
                </div>
                <div style={{width: 112, color: '#9CA3AF', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', lineHeight: 16.80, wordWrap: 'break-word'}}>Search</div>
            </div>
        </div>
        <div style={{paddingLeft: 16, paddingRight: 16, paddingTop: 15, paddingBottom: 15, background: 'white', justifyContent: 'center', alignItems: 'center', gap: 35, display: 'flex'}}>
            <div style={{color: '#4C587C', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', height: 17, wordWrap: 'break-word'}}>Launches</div>
            <div style={{color: '#4C587C', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', height: 17, wordWrap: 'break-word'}}>Categories</div>
            <div style={{color: '#4C587C', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', height: 17, wordWrap: 'break-word'}}>Community</div>
            <div style={{color: '#4C587C', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', height: 17, wordWrap: 'break-word'}}>About Us</div>
        </div>
        <div style={{justifyContent: 'flex-start', alignItems: 'flex-end', gap: 8, display: 'flex'}}>
            <div style={{paddingLeft: 20, paddingRight: 20, paddingTop: 9, paddingBottom: 9, background: 'rgba(1, 127, 64, 0.10)', borderRadius: 5, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', gap: 20, display: 'flex'}}>
                <div style={{color: '#017F40', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '500', height: 17, lineHeight: 16.80, wordWrap: 'break-word'}}>Create an account</div>
            </div>
            <div style={{paddingTop: 9, paddingBottom: 10, paddingLeft: 19, paddingRight: 20, background: '#017F40', borderRadius: 5, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', display: 'flex'}}>
                <div style={{color: 'white', fontSize: 14, fontFamily: 'Rethink Sans', fontWeight: '400', height: 17, lineHeight: 16.80, wordWrap: 'break-word'}}>Sign in</div>
            </div>
        </div>
    </header>
  );
}