import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/navBar'; // Corrected import path
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Informed AI - Your buying agent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Informed AI - Your buying agent</title>
        <meta name="description" content="Get all the insights and data you need to make confident decisions on sales tools—no salespeople required." /> 
        <meta name="keywords" content="B2B SaaS, AI buyer, sales tools" />
        <meta property="og:title" content="Informed AI - Your buying agent" />
        <meta property="og:description" content="Get all the insights and data you need to make confident decisions on sales tools—no salespeople required." /> 
        <meta property="og:image" content="URL to your image" /> 
        <meta property="og:url" content="URL to your page" /> 
        <meta name="twitter:card" content="summary_large_image" /> 
        <meta name="twitter:title" content="Informed AI - Your buying agent" /> 
        <meta name="twitter:description" content="Get all the insights and data you need to make confident decisions on sales tools—no salespeople required." /> 
        <meta name="twitter:image" content="URL to your image" />
      </Head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
