'use client';
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FkQLete9amt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useEffect, useState } from 'react';

export default function NavBar() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [windowWidth, setWindowWidth] = useState(typeof window !== 'undefined' ? window.innerWidth : 0);

  useEffect(() => {
    if (typeof window !== 'undefined' && localStorage.getItem('token')) {
      setIsLoggedIn(true);
    }

    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('token');
    window.location.reload();
  };

  const headerStyle = {
    width: '100%',
    height: '60px', // Reduced height for a shorter navbar
    paddingLeft: 40, // Increased padding for more space
    paddingRight: 40, // Increased padding for more space
    paddingTop: 5,
    background: 'white',
    justifyContent: 'space-between',
    alignItems: 'center',
    display: 'inline-flex',
  };

  const firstDivStyle = {
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 5,
    display: 'flex',
    height: '100%', // Set to 100% to fit the new header height
  };

  return (
    <header style={headerStyle}>
        <div style={firstDivStyle}>
            <img style={{width: 150, position: 'relative'}} src="/logo-green.png" /> {/* Adjusted logo width */}
        </div>
        {isLoggedIn ? (
            <div style={{ height: '100%', paddingLeft: 10, paddingRight: 10, paddingTop: 3, paddingBottom: 3, borderRadius: 5, overflow: 'hidden', justifyContent: 'flex-start', alignItems: 'center', gap: 8, display: 'inline-flex', background: 'none', border: 'none', cursor: 'pointer'}}>
                <button onClick={handleLogout} style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center' }}>
                    <img style={{width: 19.45, height: 20, marginRight: 8}} src="/material-symbols_logout.svg" alt="Logout Icon" />
                    <div style={{color: '#4C587C', fontSize: 14, fontFamily: 'Open Sans', fontWeight: '400', wordWrap: 'break-word'}}>Logout</div>
                </button>
            </div>
        ) : (
            <div style={{justifyContent: 'flex-start', alignItems: 'flex-end', gap: 8, display: 'flex'}}>
                <button onClick={() => window.location.href = '/signup'} style={{paddingLeft: 15, paddingRight: 15, paddingTop: 6, paddingBottom: 6, background: 'rgba(1, 127, 64, 0.10)', borderRadius: 5, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', gap: 20, display: 'flex'}}>
                    <div style={{color: '#017F40', fontSize: 14, fontFamily: 'Open Sans', fontWeight: '500', height: 17, wordWrap: 'break-word', lineHeight: '17px', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>Create an account</div>
                </button>
                <button onClick={() => window.location.href = '/signin'} style={{paddingTop: 6, paddingBottom: 6, paddingLeft: 15, paddingRight: 15, background: '#017F40', borderRadius: 5, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', display: 'flex'}}>
                    <div style={{color: 'white', fontSize: 14, fontFamily: 'Open Sans', fontWeight: '400', height: 17, wordWrap: 'break-word', lineHeight: '17px', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>Sign in</div>
                </button>
            </div>
        )}
    </header>
  );
}